version: "3.5"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    environment:
      #MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      INSTANCE_NAME: "${INSTANCE_NAME}"
      PROJECT_COLOR: "${PROJECT_COLOR}"
    container_name: ${DOCKER_IMAGE_PREFIX}php
    restart: unless-stopped 
  apache:
    build:
      context: './apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "${EXTERNAL_APACHE_PORT}:80"
      - "${EXTERNAL_APACHE_HTTPS_PORT}:443"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    container_name: ${DOCKER_IMAGE_PREFIX}apache
    restart: unless-stopped 
  mariadb:
    image: mariadb:${MYSQL_VERSION}
    command: 
      - mariadbd
    restart: unless-stopped
    ports:
      - "${EXTERNAL_MYSQL_PORT}:3306"
    volumes:
            - ./mysql/data/:/var/lib/mysql
    networks:
      - backend
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: ${DOCKER_IMAGE_PREFIX}mariadb
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PHPMYADMIN_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - backend
    environment:
      PMA_HOST: "mariadb"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    container_name: ${DOCKER_IMAGE_PREFIX}phpmyadmin
    
networks:
  frontend:
    name: ${DOCKER_IMAGE_PREFIX}frontend
  backend:
    name: ${DOCKER_IMAGE_PREFIX}backend
volumes:
    data: